name: ValidateBlocklists

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/blocklistValidate.yml"
      - ".eslintrc.cjs"
      - ".prettierignore"
      - "*.toml"
      - "*.Dockerfile"
      - "*.js"
      - "*/*.js"
      - ".husky/*"
      - ".prettierrc.json"
      - "LICENSE"
      - "README.md"
  pull_request:
  repository_dispatch:

env:
  INDIR: "blocklistfiles"
  OUTDIR: "result"
  S3DIR: "blocklists"
  BLCONFIG: "config.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Validate blocklist config
        run: python3 download.py
